### PR TITLE
Fix Continuous Integration

### PR DESCRIPTION
**Pull request by smortex**
#### Pull Request (PR) description

Travis CI is currently broken.  Fix some issues found while inspecting the situation and attempting to unbreak CI.

#### This Pull Request (PR) fixes the following issues

No actual issues fixed, but it should help making #290 and #291 pass.

### CODE REVIEW

**Comment by Dan33l** [comment]
@smortex ia ora na.

Thank you for this PR. It looks that only puppet6-nightly fail. I don't understand why. I'll make some checks locally as soon as possible.

**Comment by Dan33l** [comment]
@smortex this PR is interesting with `sleep` at right place and URL correctly called. Locally i ran it several times with centos7 and puppet6-nightly without any fail.

In the last push, job in Travis failed because of true fail, probably linked to network issue or something like this.

I asked to people with admin power in travis to rerun manually this uniq failing job. It should pass.
If so, i agree to merge the PR as is.

**Comment by smortex** [comment]
@Dan33l sure. I can also force commit or squash commits so that Travis re-schedule a build, but it takes about 2 hours to run a build…

I am not sure the sleep really helps here: as far as I can see, the build failures where the same when the sleep was running too early.  Maybe it can be removed?

**Comment by Dan33l** [comment]
Where it was previously in the code, the `sleep` was executed before the pp code is applied. Now, where it is located, it looks to be applied after the pp code is applied. Gitlab is a bundle of several softwares, so it should be interesting to wait all process are started before to test the result.

**Comment by smortex** [comment]
For sure it does not harm, we can leave it as it is now.  :+1:

**Pull request merged**
