### PR TITLE
Separate data from code and move defaults to common.yaml

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
Only parameters that _have_ to be configured by hiera (subject to hierarchical constraints) should be in hiera for a component module. This reduces complexity across versions of puppet and makes it easier for users to implement the module and rule out hiera as a source of bugs in their deployments.

**Comment by alexjfisher** [comment]
Reopening as I think this needs further discussion and hopefully we can get some sort of consensus.

**Comment by Dan33l** [comment]
IMO after consensus is found, it looks useful to add it in the guide line https://voxpupuli.org/docs/#reviewing-a-module-pr.

**Comment by alexjfisher** [comment]
Maybe we *should* be following https://github.com/puppetlabs/best-practices/pull/24
This is quite a recent recommendation.  [`puppetlabs/ntp`](https://github.com/puppetlabs/puppetlabs-ntp/blob/b4dee625b2d03589ec6213ed5c087d712fddb1e8/manifests/init.pp) hasn't actually been updated.

**Comment by Dan33l** [comment]
With PR  [voxpupuli.github.io #189](https://github.com/voxpupuli/voxpupuli.github.io/pull/189), i suppose we can cose this one.
@dhoppe  ?

**Pull request closed without merging**
