### PR TITLE
Allow to set numeric values as string

### LINKED ISSUE #289: Mattermost SMTP port cannot be configured by the module
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Not applicable
- Ruby: Not applicable
- Distribution: Not applicable
- Module version: 2.x+

## How to reproduce (e.g Puppet code you use)

Configure e-mail in mattermost:

```puppet
class { 'gitlab':
  # ...
  mattermost => {
    env => {
      'MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS' => 'true',  # lint:ignore:quoted_booleans
      'MM_EMAILSETTINGS_SMTPPORT'               => '25',
      'MM_EMAILSETTINGS_SMTPSERVER'             => 'localhost',
    },
  },
}
```

Apply the catalog.

## What are you seeing

Catalog fails to apply: `/etc/gitlab/gitlab.rb` is updated according to the change, but `gitlab_reconfigure` fails with "had an error: Chef::Exceptions::ValidationFailed: Property content must be one of: String, nil!
 You passed 25."                           

The `/etc/gitlab/gitlab.rb` file indeed has the value as an Integer and not a String as expected:

```ruby
mattermost['env'] = { [...], "MM_EMAILSETTINGS_SMTPPORT"=>25, [...] }
```

Quoting the number and triggering `/usr/bin/gitlab-ctl reconfigure` manually does what is expected.

## What behavior did you expect instead

Since I put a string (`'25'`) in my configuration, I expect the module to output a string into `/etc/gitlab/gitlab.rb` and not turn it into a number.

The numify function is responsible for this, but the name makes me think that removing this feature will break things:
https://github.com/voxpupuli/puppet-gitlab/blob/51628afdacd8ffaf4df138a6f1d55c5e5202a1e4/templates/gitlab.rb.erb#L21-L31

## Output log

```
[...]
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: Recipe: mattermost::enable
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * account[Mattermost user and group] action create
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     * group[Mattermost user and group] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     * linux_user[Mattermost user and group] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:      (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * directory[/var/opt/gitlab/mattermost] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * directory[/var/log/gitlab/mattermost/] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * directory[/var/opt/gitlab/mattermost/data] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * directory[/var/opt/gitlab/mattermost/plugins] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * directory[/var/opt/gitlab/mattermost/client-plugins] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * file[/var/log/gitlab/mattermost/mattermost.log] action create (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * postgresql_user[gitlab_mattermost] action create
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     * execute[create gitlab_mattermost postgresql user] action run (skipped due to not_if)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:      (up to date)      
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * execute[create mattermost_production database] action run (skipped due to not_if)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * ruby_block[populate mattermost configuration options] action run
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     - execute the ruby block populate mattermost configuration options
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * remote_file[/var/opt/gitlab/mattermost/config.json] action create_if_missing (up to date)
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:   * env_dir[/var/opt/gitlab/mattermost/env] action create
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ================================================================================
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     Error executing action `create` on resource 'env_dir[/var/opt/gitlab/mattermost/env]'
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ================================================================================
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     Chef::Exceptions::ValidationFailed
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ----------------------------------
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     Property content must be one of: String, nil!  You passed 25.
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     Cookbook Trace:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ---------------
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/env_dir.rb:42:in `block (3 levels) in class_from_file'
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/env_dir.rb:41:in `block (2 levels) in class_from_file'
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/env_dir.rb:40:in `each'
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/env_dir.rb:40:in `block in class_from_file'
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     Resource Declaration:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ---------------------
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/mattermost/recipes/enable.rb
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     124: env_dir File.join(mattermost_home, 'env') do
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     125:   variables lazy { MattermostHelper.get_env_variables(node).merge(node['mattermost']['env']) }
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     126:   notifies :restart, "service[mattermost]"
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     127: end
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     128:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     Compiled Resource:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ------------------
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/mattermost/recipes/enable.rb:124:in `from_file'
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     env_dir("/var/opt/gitlab/mattermost/env") do
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:       action [:create]
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:       default_guard_interpreter :default
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:       declared_type :env_dir
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:       cookbook_name "mattermost"
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:       recipe_name "enable"
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:       variables {"MM_SERVICESETTINGS_SITEURL"=>"https://mattermost.example.com", "MM_SERVICESETTINGS_LISTENADDRESS"=>"127.0.0.1:8065", "MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS"=>" gitlab.example.com", "MM_SERVICESETTINGS_ENABLEAPITEAMDELETION"=>"true", "MM_TEAMSETTINGS_SITENAME"=>"GitLab Mattermost", "MM_SQLSETTINGS_DRIVERNAME"=>"postgres", "MM_SQLSETTINGS_DATASOURCE"=>"user=gitlab_mattermost host=/var/opt/gitlab/postgresql port=5432 dbname=mattermost_production", "MM_SQLSETTINGS_ATRESTENCRYPTKEY"=>"xxx", "MM_LOGSETTINGS_FILELOCATION"=>"/var/log/gitlab/mattermost/", "MM_FILESETTINGS_DIRECTORY"=>"/var/opt/gitlab/mattermost/data", "MM_GITLABSETTINGS_ENABLE"=>"true", "MM_GITLABSETTINGS_SECRET"=>"xxx", "MM_GITLABSETTINGS_ID"=>"xxx", "MM_GITLABSETTINGS_SCOPE"=>"", "MM_GITLABSETTINGS_AUTHENDPOINT"=>"https://gitlab.example.com/oauth/authorize", "MM_GITLABSETTINGS_TOKENENDPOINT"=>"https://gitlab.example.com/oauth/token", "MM_GITLABSETTINGS_USERAPIENDPOINT"=>"https://gitlab.example.com/api/v4/user", "MM_PLUGINSETTINGS_DIRECTORY"=>"/var/opt/gitlab/mattermost/plugins", "MM_PLUGINSETTINGS_CLIENTDIRECTORY"=>"/var/opt/gitlab/mattermost/client-plugins", "SSL_CERT_DIR"=>"/opt/gitlab/embedded/ssl/certs/", "MM_EMAILSETTINGS_ENABLESIGNINWITHEMAIL"=>"false", "MM_EMAILSETTINGS_ENABLESIGNUPWITHEMAIL"=>"false", "MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS"=>"true", "MM_EMAILSETTINGS_SMTPPORT"=>25, "MM_EMAILSETTINGS_SMTPSERVER"=>"localhost", "MM_SERVICESETTINGS_ENABLEINCOMINGWEBHOOKS"=>"true", "MM_SERVICESETTINGS_ENABLEOUTGOINGWEBHOOKS"=>"true", "MM_SUPPORTSETTINGS_SUPPORTEMAIL"=>"contact@example.com"}
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     end
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     System Info:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ------------
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     chef_version=13.6.4
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     platform=debian
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     platform_version=9.6
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     ruby=ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]    
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     program_name=/opt/gitlab/embedded/bin/chef-client
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:     executable=/opt/gitlab/embedded/bin/chef-client      
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: Running handlers:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: There was an error running gitlab-ctl reconfigure:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: env_dir[/var/opt/gitlab/mattermost/env] (mattermost::enable line 124) had an error: Chef::Exceptions::ValidationFailed: Property content must be one of: String, nil!
 You passed 25.
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns:
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: Running handlers complete
Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: Chef Client failed. 2 resources updated in 05 seconds
Error: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]: Failed to call refresh: '/usr/bin/gitlab-ctl reconfigure' returned 1 instead of one of [0]
Error: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]: '/usr/bin/gitlab-ctl reconfigure' returned 1 instead of one of [0]
Info: Class[Gitlab::Config]: Unscheduling all events on Class[Gitlab::Config]
Notice: /Stage[main]/Gitlab::Service/Service[gitlab-runsvdir]: Dependency Exec[gitlab_reconfigure] has failures: true
Warning: /Stage[main]/Gitlab::Service/Service[gitlab-runsvdir]: Skipping because of failed dependencies
Notice: Applied catalog in 38.75 seconds
```

### PR DESCRIPTION
**Pull request by smortex**
#### Pull Request (PR) description
When the user sets a value to the string representation of a number (e.g. `"25"`), the current code turn this into the number itself (`25` in this case).

#### This Pull Request (PR) fixes the following issues
Fixes #289

### CODE REVIEW

**Comment by smortex** [comment]
Build failures for beaker checks seems unrelated :-/

**Comment by Dan33l** [comment]
@smortex i merged #292 , you can rebase this PR.

**Comment by LongLiveCHIEF** [comment]
This would be an upstream problem. We've had many issues before allowing integers as strings.

**Comment by LongLiveCHIEF** [comment]
I'm going to pull together some relevant PR's and issues from the past, sit tight.

**Comment by LongLiveCHIEF** [comment]
@smortex I saw the tests you added for acceptance, and I think it will help us add some test that I think will be needed to accept this. 

Over the years, we've found several times where trying to coerce values to a non approved type (by puppet's standards) will cause problems once gitlab fixes the type validation for the affected config upstream.

While this specific mattermost setting might work incorrectly with an integer, I believe the opposite to be true for other settings that require an integer.  

I think we need to add tests for some of those other settings as well before we accept this.  Some examples are LDAP ports, nginx ports, docker ports, and ports of various HA components.

In the past we've decided not to allow to decorator function to coerce values that would be errors to the puppet syntax validator, and we've had success working with gitlab to fix this upstream.

It's possible it _is_ fixed upstream, and you're using a pre-patched version of gitlab-omnibus.

**Comment by smortex** [comment]
Sorry @LongLiveCHIEF I don't understand what you are requesting exactly.  Can you be more directive on what you are expecting?  Thanks!

**Comment by LongLiveCHIEF** [comment]
So here's what we've discovered over the years. Only valid puppet data types should be passed to the decorator. Anything that's _not_ a valid data type, and causes an error with install/reconfig as a result, is an upstream bug that should be filed with [gitlab.com/gitlab-org/omnibus-gitlab](https://gitlab.com/gitlab-org/omnibus-gitlab/issues).

We've had many issues in the past where quoting integer values causes config to _fail_ (ex... see https://github.com/voxpupuli/puppet-gitlab/pull/109). I worked directly with the gitlab engineering team on this, and the result was that the `gitlab.rb` had type verification and coercion built into it, such that if you _do_ pass an integer as a string, it would be converted to an integer before the chef execution triggered by `gitlab-ctl reconfigure` is run.

We also _don't_ want to allow to decorator to accept any values that a puppet syntax validator will error out on (see decision in https://github.com/voxpupuli/puppet-gitlab/pull/226), Such as passing integers or booleans as strings (see https://github.com/voxpupuli/puppet-gitlab/issues/225).

If you're running into an error where configuration only succeeds if you are passing an integer as a string, then you're either using a old/unsupported version of gitlab omnibus, or there's a regression upstream that should be a bug report opened in the gitlab-omnibus repo itself.

We have to be careful about what we accept into the puppet module. Accepting something that in essence covers a bug that exists in gitlab-omnibus, will make this module incompatible with supported version of the product it is configuring.

The only way we can accept this PR, is to make sure it doesn't break _other_ configuration items in the gitlab.rb that would fail if passed.

**Comment by LongLiveCHIEF** [comment]
I see in #289 that you are on a version of gitlab-omnibus that was EoL 4 years ago, and this issue has long since been fixed upstream.

Since this issue is not present in supported versions of the product, and since accepting this PR would cause end-user `pdk` test failures (invalid data type `integer as string`), I am closing.

**Pull request closed without merging**
