### PR TITLE
Use new gitlab gpg keys for package management

### PR DESCRIPTION
**Pull request by jkroepke**
#### Pull Request (PR) description
As document in https://docs.gitlab.com/omnibus/update/package_signatures gitlab gpg keys expire soon and needs to be replace with new one.

The old key is valid until 2020-04-15 while is new keys starts at 2020-04-06.

A release of this module in this time slot should useful to avoid some local breaking changes.

This PR is created at 2020-03-28. I except test failures until 2020-04-06.

### CODE REVIEW

**Comment by dhoppe** [comment]
@jkroepke You also need to cover the RSpec checks for RHEL, since the URL has changed.

**Comment by jkroepke** [comment]
Unit tests are green now. ITs should work in 3 days.

**Comment by baurmatt** [comment]
I don't like the fact that we have to wait until the key is active (and the old one is inactive) to merge/release this. What do you think about adding both keys and removing the old one in a couple of days/weeks/months?

**Comment by dhoppe** [comment]
@baurmatt Just take a look at #333. @dnsmichi explained how to change the configuration manually. It should not be a problem to merge this pull request on time and create a new release.

**Comment by dhoppe** [comment]
@baurmatt You do not need to reopen this pull request, to trigger an Travis CI build. The result will not change, because GitLab still offers the old GPG key. I already contacted the support via Twitter.

**Comment by baurmatt** [comment]
> @baurmatt You do not need to reopen this pull request, to trigger an Travis CI build. The result will not change, because GitLab still offers the old GPG key. I already contacted the support via Twitter.

Interesting, that explains the failing test ;)

**Comment by jkroepke** [comment]
Since gitlab is a global team, they should always announce dates with timezones ...

**Comment by dnsmichi** [comment]
It is hard to track down when things are exactly done, especially when there's a certain chance that assignees change and so will timezones then. I can understand your concerns too, still, not so easy ;)

I'd recommend to follow the infrastructure group for these kind of changes. Luckily everything is developed and discussed in the open :) I just checked in there too, no changes to the issue yet.

https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/9576

**Comment by dhoppe** [comment]
@JanKoppe You can trigger a rebuild after logging into the Travis CI web interface. I already did that, but there is still an issue regarding CentOS.

**Comment by jkroepke** [comment]
Looking at 

https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.repo?os=centos&dist=7&source=script

the yum config doesn't need to be change since the gpg key redirects to the new location:

```
curl -sI https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey | grep Location
Location: https://packages.gitlab.com/gpg.key
```

**Pull request merged**
