### PR TITLE
initial modulesync

### PR DESCRIPTION
**Pull request by tobru**
This is the first modulesync run:

```
msync update -m "initial modulesync" -b "modulesync" -f "puppet-gitlab"
```

### CODE REVIEW

**Comment by tobru** [comment]
@bastelfreak @rnelson0 I need some help here to get tests pass:
* The complaints of RuboCop are not clear to me and are a whole lot (325 offenses). Maybe we can skip them for now? Or someone knows how to fix them?
* The failed rspec test `rspec ./spec/classes/cirunner_spec.rb:95 # gitlab::cirunner supported operating systems gitlab::cirunner class OS-independent behavior with default parameters should contain Gitlab::Runner[test_runner] that requires Exec[gitlab-runner-restart]` also is not something I'm able to fix right now

Would be great to get this PR merged soon so we can cut a first official Forge release under the Vox Pupuli umbrella.

Thanks for any help

**Comment by walterheck** [comment]
`metadata.json` also needs to be adjusted to point to voxpupuli I think?

**Comment by tobru** [comment]
@walterheck Yes, this will happen in #173 

@rnelson0 @bastelfreak Would be very great if we could proceed here. Any ideas how to get the failing tests fixed?

**Comment by rnelson0** [comment]
The puppet error is pretty simple, use a `let (:pre_condition)` like [here](https://github.com/rnelson0/puppet-certs/blob/0ab44779449f97551c43f77c290f68af2f5900a2/spec/defines/vhost_spec.rb#L4) include the external resource.

The rubocop ones are more tedious. You can probably run `bundle exec rubocop -a` to `autocorrect` most of the errors. It's not perfect, so there might be bad fixes, or things it cannot fix, and you will need to fix those yourself. The errors are *generally* descriptive but let us know if you need assistance with anything in particular.

**Comment by bastelfreak** [comment]
We should get this merged and don't spend too much time on rubocop warnings in spec files. IMO it's okay to disable the specific cops in the spec files that can't be autofixed - at least for now.

**Comment by tobru** [comment]
Now the only failing check:

```
Failures:
  1) gitlab::cirunner supported operating systems gitlab::cirunner class OS-independent behavior with default parameters should contain Gitlab::Runner[test_runner] that requires Exec[gitlab-runner-restart]
     Failure/Error: it { is_expected.to contain_gitlab__runner('test_runner').that_requires('Exec[gitlab-runner-restart]') }
       expected that the catalogue would contain Gitlab::Runner[test_runner]
     # ./spec/classes/cirunner_spec.rb:95:in `block (5 levels) in <top (required)>'
Finished in 8.33 seconds (files took 3.18 seconds to load)
22 examples, 1 failure
Failed examples:
rspec ./spec/classes/cirunner_spec.rb:95 # gitlab::cirunner supported operating systems gitlab::cirunner class OS-independent behavior with default parameters should contain Gitlab::Runner[test_runner] that requires Exec[gitlab-runner-restart]
```

Does anyone have the possibility to fix this?

**Pull request merged**
