### PR TITLE
Transfer module to Vox Pupuli

### PR DESCRIPTION
**Pull request by tobru**
This solves #171

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @tobru, we need to do a modulesync before we can release. I will try to do this in the next days.

**Comment by tobru** [comment]
Hi @bastelfreak. I'll also try to do it, maybe I (finally) find some time tomorrow... Will let you know.

**Comment by tobru** [comment]
@bastelfreak Create PR #174 with inital modulesync. What do you think? Save to merge?

**Comment by tobru** [comment]
I'll then rebase this PR to the merged modulesync and prepare everything for a proper release.

**Comment by tobru** [comment]
Merged #181 into master with initial modulesync and rebased this PR for merging into master.

**Pull request merged**
